/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGocampingConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API

#import "GTLGocampingConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeGocampingUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";

// GTLGocamping - TripRSVPStatus
NSString * const kGTLGocamping_TripRSVPStatus_No      = @"NO";
NSString * const kGTLGocamping_TripRSVPStatus_Pending = @"PENDING";
NSString * const kGTLGocamping_TripRSVPStatus_Yes     = @"YES";
