/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGocampingMember.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API
// Classes:
//   GTLGocampingMember (0 custom class methods, 4 custom properties)

#import "GTLGocampingMember.h"

// ----------------------------------------------------------------------------
//
//   GTLGocampingMember
//

@implementation GTLGocampingMember
@dynamic age, familyId, identifier, name;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
