/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGocamping_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API

//#import "GTLGocampingConstants.m"
//
//#import "GTLGocampingCampingTrip.m"
//#import "GTLGocampingCampingTripCollection.m"
//#import "GTLGocampingCampingTripValidationResult.m"
//#import "GTLGocampingCampingTripWrapper.m"
//#import "GTLGocampingExpense.m"
//#import "GTLGocampingExpenseCollection.m"
//#import "GTLGocampingFamiliesWrapper.m"
//#import "GTLGocampingFamily.m"
//#import "GTLGocampingFamilyCollection.m"
//#import "GTLGocampingFamilyRSVPWrapper.m"
//#import "GTLGocampingGeoPt.m"
//#import "GTLGocampingMember.m"
//#import "GTLGocampingMemberCollection.m"
//#import "GTLGocampingUserAccount.m"
//
//#import "GTLQueryGocamping.m"
//#import "GTLServiceGocamping.m"
