/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGocampingGeoPt.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API
// Classes:
//   GTLGocampingGeoPt (0 custom class methods, 2 custom properties)

#import "GTLGocampingGeoPt.h"

// ----------------------------------------------------------------------------
//
//   GTLGocampingGeoPt
//

@implementation GTLGocampingGeoPt
@dynamic latitude, longitude;
@end
