/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGocampingFamily.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API
// Classes:
//   GTLGocampingFamily (0 custom class methods, 9 custom properties)

#import "GTLGocampingFamily.h"

// ----------------------------------------------------------------------------
//
//   GTLGocampingFamily
//

@implementation GTLGocampingFamily
@dynamic email, expenseIds, fullName, identifier, memberIds, phoneNumber,
         totalOwedExpenseAmount, totalSpentExpenseAmount, tripRSVPStatus;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"expenseIds" : [NSNumber class],
    @"memberIds" : [NSNumber class]
  };
  return map;
}

@end
