/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGocampingCampingTripValidationResult.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API
// Classes:
//   GTLGocampingCampingTripValidationResult (0 custom class methods, 2 custom properties)

#import "GTLGocampingCampingTripValidationResult.h"

// ----------------------------------------------------------------------------
//
//   GTLGocampingCampingTripValidationResult
//

@implementation GTLGocampingCampingTripValidationResult
@dynamic errorMessage, valid;
@end
