/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGocampingFamiliesWrapper.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API
// Classes:
//   GTLGocampingFamiliesWrapper (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLGocampingFamily;

// ----------------------------------------------------------------------------
//
//   GTLGocampingFamiliesWrapper
//

@interface GTLGocampingFamiliesWrapper : GTLObject
@property (nonatomic, retain) NSArray *families;  // of GTLGocampingFamily
@end
