/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGocampingFamilyRSVPWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API
// Classes:
//   GTLGocampingFamilyRSVPWrapper (0 custom class methods, 4 custom properties)

#import "GTLGocampingFamilyRSVPWrapper.h"

// ----------------------------------------------------------------------------
//
//   GTLGocampingFamilyRSVPWrapper
//

@implementation GTLGocampingFamilyRSVPWrapper
@dynamic campingTripId, familyId, familyRSVPedResponse, totalMembersComing;
@end
