/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGocampingFamilyCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API
// Classes:
//   GTLGocampingFamilyCollection (0 custom class methods, 1 custom properties)

#import "GTLGocampingFamilyCollection.h"

#import "GTLGocampingFamily.h"

// ----------------------------------------------------------------------------
//
//   GTLGocampingFamilyCollection
//

@implementation GTLGocampingFamilyCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLGocampingFamily class]
  };
  return map;
}

@end
