/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGocampingUserAccount.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API
// Classes:
//   GTLGocampingUserAccount (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLGocampingUserAccount
//

@interface GTLGocampingUserAccount : GTLObject
@property (nonatomic, retain) NSArray *campingTripsKeys;  // of NSNumber (longLongValue)
@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *fullName;
@property (nonatomic, retain) NSArray *membersKeys;  // of NSNumber (longLongValue)
@property (nonatomic, copy) NSString *password;
@property (nonatomic, retain) NSNumber *phoneNumber;  // longLongValue
@end
