/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGocampingCampingTrip.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API
// Classes:
//   GTLGocampingCampingTrip (0 custom class methods, 9 custom properties)

#import "GTLGocampingCampingTrip.h"

#import "GTLGocampingGeoPt.h"

// ----------------------------------------------------------------------------
//
//   GTLGocampingCampingTrip
//

@implementation GTLGocampingCampingTrip
@dynamic addressString, dateFrom, dateTo, familiesIds, identifier,
         locationPoint, title, totalMembersComingToTrip, totalTripExpense;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"familiesIds" : [NSNumber class]
  };
  return map;
}

@end
