/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGocampingUserAccount.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API
// Classes:
//   GTLGocampingUserAccount (0 custom class methods, 5 custom properties)

#import "GTLGocampingUserAccount.h"

// ----------------------------------------------------------------------------
//
//   GTLGocampingUserAccount
//

@implementation GTLGocampingUserAccount
@dynamic campingTripsKeys, email, fullName, membersKeys, phoneNumber;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"campingTripsKeys" : [NSNumber class],
    @"membersKeys" : [NSNumber class]
  };
  return map;
}

@end
