/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGocamping.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API

#import "GTLGocampingConstants.h"

#import "GTLGocampingCampingTrip.h"
#import "GTLGocampingCampingTripCollection.h"
#import "GTLGocampingCampingTripValidationResult.h"
#import "GTLGocampingCampingTripWrapper.h"
#import "GTLGocampingExpense.h"
#import "GTLGocampingExpenseCollection.h"
#import "GTLGocampingFamiliesWrapper.h"
#import "GTLGocampingFamily.h"
#import "GTLGocampingFamilyCollection.h"
#import "GTLGocampingFamilyRSVPWrapper.h"
#import "GTLGocampingGeoPt.h"
#import "GTLGocampingMember.h"
#import "GTLGocampingMemberCollection.h"
#import "GTLGocampingUserAccount.h"
#import "GTLGocampingFamilyCollection.m"

#import "GTLQueryGocamping.h"
#import "GTLServiceGocamping.h"
