/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGocampingCampingTripCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API
// Classes:
//   GTLGocampingCampingTripCollection (0 custom class methods, 1 custom properties)

#import "GTLGocampingCampingTripCollection.h"

#import "GTLGocampingCampingTrip.h"

// ----------------------------------------------------------------------------
//
//   GTLGocampingCampingTripCollection
//

@implementation GTLGocampingCampingTripCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLGocampingCampingTrip class]
  };
  return map;
}

@end
