/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGocampingCampingTrip.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API
// Classes:
//   GTLGocampingCampingTrip (0 custom class methods, 9 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLGocampingGeoPt;

// ----------------------------------------------------------------------------
//
//   GTLGocampingCampingTrip
//

@interface GTLGocampingCampingTrip : GTLObject
@property (nonatomic, copy) NSString *addressString;
@property (nonatomic, retain) GTLDateTime *dateFrom;
@property (nonatomic, retain) GTLDateTime *dateTo;
@property (nonatomic, retain) NSArray *familiesIds;  // of NSNumber (longLongValue)

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // longLongValue

@property (nonatomic, retain) GTLGocampingGeoPt *locationPoint;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, retain) NSNumber *totalMembersComingToTrip;  // intValue
@property (nonatomic, retain) NSNumber *totalTripExpense;  // doubleValue
@end
