/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryGocamping.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gocamping/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryGocamping (17 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLGocampingCampingTripWrapper;
@class GTLGocampingExpense;
@class GTLGocampingFamiliesWrapper;
@class GTLGocampingFamilyRSVPWrapper;
@class GTLGocampingMember;
@class GTLGocampingUserAccount;

@interface GTLQueryGocamping : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, assign) long long campingTripId;
@property (nonatomic, assign) long long expenseID;
@property (nonatomic, assign) long long familyId;
@property (nonatomic, assign) long long familyID;
@property (nonatomic, assign) long long memberId;
@property (nonatomic, assign) long long registeredPhoneNumber;

#pragma mark - Service level methods
// These create a GTLQueryGocamping object.

// Method: gocamping.addExpense
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
+ (instancetype)queryForAddExpenseWithObject:(GTLGocampingExpense *)object
                               campingTripId:(long long)campingTripId;

// Method: gocamping.addMember
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
+ (instancetype)queryForAddMemberWithObject:(GTLGocampingMember *)object
                                   familyID:(long long)familyID
                              campingTripId:(long long)campingTripId;

// Method: gocamping.createCampingTrip
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
// Fetches a GTLGocampingCampingTripValidationResult.
+ (instancetype)queryForCreateCampingTripWithObject:(GTLGocampingCampingTripWrapper *)object;

// Method: gocamping.deleteCampingTrip
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
+ (instancetype)queryForDeleteCampingTripWithCampingTripId:(long long)campingTripId;

// Method: gocamping.deleteExpense
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
+ (instancetype)queryForDeleteExpenseWithExpenseID:(long long)expenseID
                                     campingTripId:(long long)campingTripId;

// Method: gocamping.deleteFamily
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
+ (instancetype)queryForDeleteFamilyWithFamilyId:(long long)familyId;

// Method: gocamping.deleteMember
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
+ (instancetype)queryForDeleteMemberWithMemberId:(long long)memberId
                                        familyId:(long long)familyId
                                   campingTripId:(long long)campingTripId;

// Method: gocamping.deletUser
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
+ (instancetype)queryForDeletUserWithRegisteredPhoneNumber:(long long)registeredPhoneNumber;

// Method: gocamping.getAllFamilyExpenses
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
// Fetches a GTLGocampingExpenseCollection.
+ (instancetype)queryForGetAllFamilyExpensesWithFamilyID:(long long)familyID;

// Method: gocamping.getAllFamilyMembers
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
// Fetches a GTLGocampingMemberCollection.
+ (instancetype)queryForGetAllFamilyMembersWithFamilyId:(long long)familyId;

// Method: gocamping.getCampingTrips
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
// Fetches a GTLGocampingCampingTripCollection.
+ (instancetype)queryForGetCampingTripsWithObject:(GTLGocampingUserAccount *)object;

// Method: gocamping.getFamily
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
// Fetches a GTLGocampingFamily.
+ (instancetype)queryForGetFamilyWithFamilyID:(long long)familyID;

// Method: gocamping.getMember
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
// Fetches a GTLGocampingMember.
+ (instancetype)queryForGetMemberWithMemberId:(long long)memberId;

// Method: gocamping.inviteFamilies
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
+ (instancetype)queryForInviteFamiliesWithObject:(GTLGocampingFamiliesWrapper *)object
                                   campingTripId:(long long)campingTripId;

// Method: gocamping.registerUser
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
+ (instancetype)queryForRegisterUserWithObject:(GTLGocampingUserAccount *)object;

// Method: gocamping.rsvpForTheFamily
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
+ (instancetype)queryForRsvpForTheFamilyWithObject:(GTLGocampingFamilyRSVPWrapper *)object;

// Method: gocamping.updateExpense
//  Authorization scope(s):
//   kGTLAuthScopeGocampingUserinfoEmail
+ (instancetype)queryForUpdateExpenseWithObject:(GTLGocampingExpense *)object;

@end
